//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthenticationToken
    {
        public string Token { get; set; }
        public string IDUsuario { get; set; }
        public string Pwd { get; set; }
        public System.DateTime FechaExpiracion { get; set; }
        public System.DateTime FechaUltLogin { get; set; }
    }
}
