//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACHEEntities : DbContext
    {
        public ACHEEntities()
            : base("name=ACHEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LugaresTraslados> LugaresTraslados { get; set; }
        public DbSet<Menues> Menues { get; set; }
        public DbSet<Pedidos> Pedidos { get; set; }
        public DbSet<PedidosDetalle> PedidosDetalle { get; set; }
        public DbSet<Proveedores> Proveedores { get; set; }
        public DbSet<Restaurantes> Restaurantes { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<UsuariosAdmin> UsuariosAdmin { get; set; }
        public DbSet<Parametros> Parametros { get; set; }
        public DbSet<Productos> Productos { get; set; }
        public DbSet<PasajerosPorPedidoTraslado> PasajerosPorPedidoTraslado { get; set; }
        public DbSet<SubTipos> SubTipos { get; set; }
        public DbSet<PedidosTraslado> PedidosTraslado { get; set; }
        public DbSet<Servicios> Servicios { get; set; }
        public DbSet<PreciosProductos> PreciosProductos { get; set; }
        public DbSet<PreciosServicios> PreciosServicios { get; set; }
    }
}
