//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LugaresTraslados
    {
        public LugaresTraslados()
        {
            this.PedidosTraslado = new HashSet<PedidosTraslado>();
            this.PedidosTraslado1 = new HashSet<PedidosTraslado>();
        }
    
        public int IDLugarTraslado { get; set; }
        public int IDProveedor { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public bool Activo { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        public virtual ICollection<PedidosTraslado> PedidosTraslado { get; set; }
        public virtual ICollection<PedidosTraslado> PedidosTraslado1 { get; set; }
    }
}
