//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menues
    {
        public int IDMenu { get; set; }
        public int IDRestaurant { get; set; }
        public string TipoMenu { get; set; }
        public string Entrada { get; set; }
        public string PlatoPrincipal { get; set; }
        public string Postre { get; set; }
        public bool IncluyeBebida { get; set; }
        public string Imagen { get; set; }
        public string ImagenMenu { get; set; }
    
        public virtual Restaurantes Restaurantes { get; set; }
    }
}
