//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public int IDParametro { get; set; }
        public string TextoBeneficios { get; set; }
        public string TextoTraslados { get; set; }
        public decimal AdicionalNocturno { get; set; }
    }
}
