//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasajerosPorPedidoTraslado
    {
        public int IDPasajerosPorPedidoTraslado { get; set; }
        public Nullable<int> IDPedidoTraslado { get; set; }
        public string Nombre { get; set; }
        public string DNI { get; set; }
    
        public virtual PedidosTraslado PedidosTraslado { get; set; }
    }
}
