//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosDetalle
    {
        public int IDDetalle { get; set; }
        public int IDPedido { get; set; }
        public int IDProducto { get; set; }
        public decimal Precio { get; set; }
        public decimal PrecioOperador { get; set; }
        public Nullable<bool> Validado { get; set; }
        public Nullable<System.DateTime> FechaValidacion { get; set; }
        public Nullable<int> IDRestauranteValidacion { get; set; }
        public int CantCenas { get; set; }
        public int CantPasajeros { get; set; }
        public Nullable<int> DigitoVerficador { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
        public virtual Restaurantes Restaurantes { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
