//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreciosProductos
    {
        public int IDPrecioProducto { get; set; }
        public int IDProducto { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public decimal PrecioOperador { get; set; }
        public decimal PrecioRestaurante { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
