//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public Productos()
        {
            this.PedidosDetalle = new HashSet<PedidosDetalle>();
            this.PreciosProductos = new HashSet<PreciosProductos>();
        }
    
        public int IDProducto { get; set; }
        public string Tipo { get; set; }
        public string Entrada { get; set; }
        public string PlatoPrincipal { get; set; }
        public string Postre { get; set; }
        public bool IncluyeBebida { get; set; }
        public bool Activo { get; set; }
        public int Precio { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int PrecioOperador { get; set; }
        public int PrecioProxTemp { get; set; }
        public int PrecioOperadorProxTemp { get; set; }
    
        public virtual ICollection<PedidosDetalle> PedidosDetalle { get; set; }
        public virtual ICollection<PreciosProductos> PreciosProductos { get; set; }
    }
}
