//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public Servicios()
        {
            this.PedidosTraslado = new HashSet<PedidosTraslado>();
            this.PreciosServicios = new HashSet<PreciosServicios>();
        }
    
        public int IDServicio { get; set; }
        public int IDProveedor { get; set; }
        public string Nombre { get; set; }
        public decimal PrecioRegular { get; set; }
        public decimal PrecioPrivado { get; set; }
        public string ObservacionesRegular { get; set; }
        public string ObservacionesPrivado { get; set; }
        public bool Activo { get; set; }
        public decimal PrecioRegularNoRepresentado { get; set; }
        public decimal PrecioPrivadoNoRepresentado { get; set; }
        public int IDSubTipo { get; set; }
        public bool ServicioEspecial { get; set; }
        public bool EsPrivado { get; set; }
        public int MaxPasajeros { get; set; }
    
        public virtual ICollection<PedidosTraslado> PedidosTraslado { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual SubTipos SubTipos { get; set; }
        public virtual ICollection<PreciosServicios> PreciosServicios { get; set; }
    }
}
