//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTipos
    {
        public SubTipos()
        {
            this.Servicios = new HashSet<Servicios>();
        }
    
        public int IDSubTipo { get; set; }
        public string Lugar1 { get; set; }
        public string Lugar2 { get; set; }
        public string Lugar3 { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<Servicios> Servicios { get; set; }
    }
}
