//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Pedidos = new HashSet<Pedidos>();
            this.PedidosTraslado = new HashSet<PedidosTraslado>();
            this.PreciosServicios = new HashSet<PreciosServicios>();
        }
    
        public int IDUsuario { get; set; }
        public string TipoUsuario { get; set; }
        public string Email { get; set; }
        public string Pwd { get; set; }
        public string Empresa { get; set; }
        public string Contacto { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public bool PagoPorHabilitado { get; set; }
        public bool ServiciosEspeciales { get; set; }
    
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        public virtual ICollection<PedidosTraslado> PedidosTraslado { get; set; }
        public virtual ICollection<PreciosServicios> PreciosServicios { get; set; }
    }
}
